# Generated by Django 5.2.5 on 2025-09-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_wholesale',
            field=models.BooleanField(default=False, verbose_name='Is this a wholesale product?'),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_order',
            field=models.PositiveIntegerField(default=1, verbose_name='Minimum Order Quantity'),
        ),
    ]
