# Generated by Django 5.2.5 on 2025-08-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='የእቃው አይነት (Brand)'),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'አዲስ (Brand New)'), ('Used', 'ያገለገለ (Used)'), ('Refurbished', 'የታደሰ (Refurbished)')], max_length=20, verbose_name='ሁኔታ (Condition)'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='የሚገኝበት ቦታ (Location)'),
        ),
    ]
