# Generated by Django 5.2.5 on 2025-09-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_product_is_wholesale_product_minimum_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_wholesaler',
            field=models.BooleanField(default=False),
        ),
    ]
