# Generated by Django 5.2.5 on 2025-09-04 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options_profile_business_license_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ETB', max_length=8)),
                ('kind', models.CharField(choices=[('one_time', 'One-time'), ('subscription', 'Subscription')], default='one_time', max_length=20)),
                ('gateway', models.CharField(choices=[('chapa', 'Chapa'), ('telebirr', 'TeleBirr')], max_length=20)),
                ('tx_ref', models.CharField(max_length=64, unique=True)),
                ('provider_txn_id', models.CharField(blank=True, max_length=128)),
                ('purpose', models.CharField(max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('raw_init', models.JSONField(blank=True, default=dict)),
                ('raw_webhook', models.JSONField(blank=True, default=dict)),
                ('raw_verify', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tx_ref'], name='users_payme_tx_ref_3f9d83_idx')],
            },
        ),
    ]
